workflows:
  scripts:
    steps:
      - name: Install CocoaPods dependencies
        run: pod install
    artifacts:
      paths:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
