  scripts:
    - name: Build the .app
      script: | 
         build using project
         xcodebuild build \
            -project ""CashApp.xcodeproj" \
            -scheme "CashappSpoof" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
